DROP PROCEDURE RGHA.UPDATE_PENDENCIES;

DROP PROCEDURE RGHA.INSERT_SERVER_SERVICE;

DROP SEQUENCE  RGHA.SEQ_SERVER_SERVICE;

DROP TABLE     RGHA.SERVER_SERVICE;

DROP PROCEDURE RGHA.INSERT_SERVICE_SECTOR;

DROP SEQUENCE  RGHA.SEQ_SERVICE_SECTOR;

DROP TABLE     RGHA.SERVICE_SECTOR;

DROP PROCEDURE RGHA.INSERT_SERVICE_DEPENDENCY;

DROP SEQUENCE  RGHA.SEQ_SERVICE_DEPENDENCY;

DROP TABLE     RGHA.SERVICE_DEPENDENCY;

DROP PROCEDURE RGHA.INSERT_SERVER_ACCESS;

DROP SEQUENCE  RGHA.SEQ_SERVER_ACCESS;

DROP TABLE     RGHA.SERVER_ACCESS;

DROP PROCEDURE RGHA.INSERT_PENDENCY;

DROP SEQUENCE  RGHA.SEQ_PENDENCY;

DROP TABLE     RGHA.PENDENCY;

DROP PROCEDURE RGHA.INSERT_SERVICE;

DROP SEQUENCE  RGHA.SEQ_SERVICE;

DROP TABLE     RGHA.SERVICE;

DROP PROCEDURE RGHA.INSERT_SECTOR;

DROP SEQUENCE  RGHA.SEQ_SECTOR;

DROP TABLE     RGHA.SECTOR;

DROP PROCEDURE RGHA.INSERT_COMPANY;

DROP SEQUENCE  RGHA.SEQ_COMPANY;

DROP TABLE     RGHA.COMPANY;

DROP PROCEDURE RGHA.INSERT_SERVER;

DROP SEQUENCE  RGHA.SEQ_SERVER;

DROP TABLE     RGHA.SERVER;

DROP SEQUENCE  RGHA.SEQ_ACCESS_TYPE;

DROP PROCEDURE RGHA.INSERT_ACCESS_TYPE;

DROP TABLE     RGHA.ACCESS_TYPE;

DROP VIEW      RGHA.V_SERVICES_MONITOR;

COMMIT;